2021-06-17: Twitter API reported an error: Twitter API returned error code 401 
Traceback (most recent call last):
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 99, in paginator
    status = request(*args)
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 86, in call
    raiseError(response.status_code)
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 50, in raiseError
    raise ApiError(code=code)
api.api.ApiError: Twitter API returned error code 401
2021-06-17: Twitter API reported an error: Twitter API returned error code 401 
Traceback (most recent call last):
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 99, in paginator
    status = request(*args)
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 86, in call
    raiseError(response.status_code)
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 50, in raiseError
    raise ApiError(code=code)
api.api.ApiError: Twitter API returned error code 401
2021-06-17: Twitter API reported an error: Twitter API returned error code 401 
Traceback (most recent call last):
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 99, in paginator
    status = request(*args)
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 86, in call
    raiseError(response.status_code)
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 50, in raiseError
    raise ApiError(code=code)
api.api.ApiError: Twitter API returned error code 401
2021-06-17: Twitter API reported an error: Twitter API returned error code 401 
Traceback (most recent call last):
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 101, in paginator
    status = request(*args)
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 86, in call
    raiseError(response.status_code)
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 50, in raiseError
    raise ApiError(code=code)
api.api.ApiError: Twitter API returned error code 401
2021-06-17: Twitter API reported an error: Twitter API returned error code 401 
Traceback (most recent call last):
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 101, in paginator
    status = request(*args)
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 86, in call
    raiseError(response.status_code)
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 50, in raiseError
    raise ApiError(code=code)
api.api.ApiError: Twitter API returned error code 401
2021-06-17: Twitter API reported an error: Twitter API returned error code 401 
Traceback (most recent call last):
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 102, in paginator
    status = request(*args)
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 86, in call
    raiseError(response.status_code)
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 50, in raiseError
    raise ApiError(code=code)
api.api.ApiError: Twitter API returned error code 401
2021-06-17: Twitter API reported an error: Twitter API returned error code 401 
Traceback (most recent call last):
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 102, in paginator
    status = request(*args)
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 86, in call
    raiseError(response.status_code)
  File "C:\Users\gafel\Documents\GitHub\twittery\src\api\api.py", line 50, in raiseError
    raise ApiError(code=code)
api.api.ApiError: Twitter API returned error code 401
